[package]
name = "terminal-noise-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
crossterm = "0.28.1"
perlin-noise = { version = "0.1.0", path = "../d10-perlin-noise" }
